Duplicate objects and xsd
lanwen/rarc pull request #28
Opened 2017-05-17 13:42 UTC by viclovsky

2017-05-18 10:59 UTC, lanwen commented
pls few words to describe content

2017-05-18 14:27 UTC, lanwen commented on rarc-core/src/main/java/ru/lanwen/raml/rarc/api/ApiResourceClass.java
> +import static java.util.stream.Collectors.*;
please dont

2017-05-18 15:10 UTC, viclovsky commented on rarc-core/src/main/java/ru/lanwen/raml/rarc/api/ApiResourceClass.java
> +import static java.util.stream.Collectors.*;
ok

2017-05-18 15:59 UTC, viclovsky commented
Fix issue of generating duplicated schema classes in case when the same schema path is specified in raml file. 

After fix all schema classes will be generated in one exact  folder and will be imported for dependent files.

2017-05-18 21:57 UTC, lanwen commented
please don't use wildcard imports. And I'll merge it

2017-05-18 21:57 UTC, lanwen requested changes
rm wildcard imports

2017-05-19 12:38 UTC, lanwen commented on rarc-example/src/main/resources/api.raml
> +# NOT WORK YET
is this PR WIP now?

2017-05-19 13:10 UTC, viclovsky commented on rarc-example/src/main/resources/api.raml
> +# NOT WORK YET
No, I will fix this bug in another PR. 
XSD schema not work in master.

2017-05-19 14:27 UTC, lanwen commented on rarc-example/src/main/resources/api.raml
> +# NOT WORK YET
ok, look forward to new changes

2017-05-19 14:27 UTC, lanwen approved these changes

2017-05-19 14:28 UTC, lanwen requested changes

2017-05-19 14:28 UTC, lanwen commented on rarc-core/src/main/java/ru/lanwen/raml/rarc/util/JsonCodegen.java
> +import org.jsonschema2pojo.*;
ah

2017-05-19 15:00 UTC, merged